name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip3 install west
          sudo apt-get update
          sudo apt-get install -y \
            gcc-multilib \
            libnewlib-arm-none-eabi \
            ccache \
            device-tree-compiler \

      - name: West Init & Update
        run: |
          cd app
          west init -l config
          west update
          
      - name: Build left shield
        run: |
          cd app && west build --board seeeduino_xiao_ble \
            --shield totem_left \
            --build-dir build/totem_left
            
      - name: Build Right Shield
        run: |
          cd app && west build --board seeeduino_xiao_ble \
            --shield totem_right \
            --build-dir build/totem_right

      - name: Export uf2 files
        run: |
          cp app/build/totem_left/zephyr/zmk.uf2 totem_left.uf2
          cp app/build/totem_right/zephyr/zmk.uf2 totem_right.uf2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZMK-Firmware
          path: |
            totem_left.uf2
            totem_right.uf2
